apiVersion: v1
kind: Service
metadata:
  name: financialmanagement-service
spec:
  type: NodePort
  selector:
    app: financialmanagement
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
